# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Create img'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    # Runs a single command using the runners shell
    - name: Build
      run: |
        sudo apt-get update -y
        sudo apt-get install -y make gcc git texinfo gzip squashfs-tools
        chmod +x ./build.sh
        ./build.sh
    - name: Upload build output as artifact
      uses: actions/upload-artifact@v4
      with:
        name: img_file
        path: |
          ./*.img.gz
          ./*.img.gz.sha256
        compression-level: 9
